### ISSUE TITLE
Vibrate controller to keep awake

### ISSUE THREAD

**Issue by TimKeesRensen** [uc-vision/RovVision2#108] opened 2023-09-22 23:29 UTC
Send short vibration command occasionally to keep awake OR test different controller. Check for micro inputs to see if it is asleep?

**Comment by codedraughtsman** [comment] 2023-12-14 22:34
This has been superseded by this issue https://github.com/uc-vision/RovVision2/issues/115

**Comment by jozefeijoa** [comment] 2023-12-20 02:52
> This has been superseded by this issue #115

Indeed, will close as duplicate of #115.

**Comment by jozefeijoa** [comment] 2023-12-20 02:52
Duplicate of #115 .

**Closed by jozefeijoa** 2023-12-20 02:52 UTC
Labels: enhancement, High Priority
