### ISSUE TITLE
auto restart crashed processes (Mako cameras, GPS)

### ISSUE THREAD

**Issue by codedraughtsman** [uc-vision/RovVision2#119] opened 2023-12-14 23:37 UTC
Restarting crashed processes (Mako cameras, GPS) happens automatically

**Comment by jozefeijoa** [comment] 2023-12-19 03:23
This is a duplicate of #135, so closing this as #135 is more general and covers all driver reliability issues.

**Closed** 2023-12-19 03:25 UTC
